---
title: "Milestone 3"
author: "Molly Chiang"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary of "Education and Voting Conservative: Evidence from a Major Schooling Reform in Great Britain"

This paper uses data from the results of the 1947 high school leaving age reform in Great Britain, to analyze how additional years in high school affect political preferences--namely in voting for the Conservative Party. In 1947, Great Britain changed the high school leaving age from 14 to 15, this induced almost half the student population to stay in school for 1 or 2 more years. Data from the 10 British elections between 1947 and 2010 was then used to compare voters young enough to have been effected by the reform to those who were too old using regression discontinuity. The results of data analysis revealed staying in high school for longer substantially increased likelihood to vote for the Conservative Party (staying one extra year increased probailitiy of voting Conservative by almost 12 percentage points). This supports the previously studied fact that high school is extremely pertinent to political opinions later in life. In addition, this significant finding indicates the education reform of 1947 may have had an even greater affect on politics and election results nationwide over many years than ever expected.

The repo for replication of this paper is located at: https://github.com/mollyechiang/1006_milestone_3

